### ISSUE TITLE
Mana text bug

### ISSUE THREAD

**Issue by bijlmermist** [RomanSpector/UnitFrameLayers#1]
Hey. I am experiencing (I would consider it) a bug when using UnitFrameLayers and having StatusText for player enabled and while i am casting. 

https://imgur.com/a/8uVlpXA

**Comment by RomanSpector** [comment]
Is there a sure way to repeat the bug? Because I can't reproduce it

**Comment by bijlmermist** [comment]
UnitFrameLayers is the only Addon that is enabled. Idk what the problem might be here:

https://youtu.be/AtTbydoS_BY

**Comment by RomanSpector** [comment]
Do you have the latest version of the addon? Is there this line in it? 
```lua
currValue = currValue - Round(predictedCost);
```
https://github.com/RomanSpector/UnitFrameLayers/blob/main/UnitFrameLayers/UnitFrame.lua#L341

**Comment by bijlmermist** [comment]
Oh, actually, I had downloaded the latest version earlier but put the older version in my wow folder and was too stupid to notice.

It works now. Thank you a lot!
